name: hybrid_search_meili
channels:
  - conda-forge
  - pytorch
  - defaults
dependencies:
  - python=3.11
  - setuptools
  - sentence-transformers
  - typer
  - pip:
      - langchain>=0.3.0
      - langchain-huggingface>=0.1.0
      - transformers>=4.43.3
      - meilisearch
      - twine
      - pycomfort>=0.0.15
  